# Generated by Django 5.0.6 on 2024-07-25 19:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='resumen',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
